title: Taking a photograph with PiCamera
hero_image: images/banner.png
description: Learn how to use the PiCamera to take a photograph
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: ""
technologies: ""
steps:
  - title: Taking a photo
