title: Taking a photograph with PiCamera
hero_image: images/banner.png
description: Learn how to use the PiCamera to take a photograph
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
ingredient: true
steps:
  - title: Step one
