title: Taking a photograph with PiCamera
hero_image: images/banner.png
description: Learn how to use picamera to take a photograph with the Camera Module
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Taking a photo
